>

version: 0.2

phases:
  build:
    commands:
        - echo "entered in buildspec phase..."
        - mvn clean package
  post_build:
    commands:
        - echo "build completed..."
  artifacts:
    files:
        - target/hello-world.war
    discard-paths: yes                

-------------------------------------------------------

version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes

#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:

phases:
  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command

#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson

#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location

#cache:
  #paths:
    # - paths



>-------------------------------------------------------------------------------------------    
      







Review

Step 1: Choose pipeline settings
Pipeline settings
Pipeline name
testapp
Artifact location
A new Amazon S3 bucket will be created as the default artifact store for your pipeline
Service role name
AWSCodePipelineServiceRole-ap-south-1-testapp

Step 2: Add source stage
Source action provider
Source action provider
GitHub (Version 1)
PollForSourceChanges
false
Repo
war_project
Owner
swapnilgit1
Branch
master

Step 3: Add build stage
Build action provider
Build action provider
AWS CodeBuild
ProjectName
testapp

Step 4: Add deploy stage
Deploy action provider
Deploy action provider
AWS Elastic Beanstalk
ApplicationName
testapp
EnvironmentName
Testapp-env
Create pipeline
Previous



 