version: 0.2

phases:
  build:
    commands:
        - echo "entered in buildspec phase..."
        - mvn clean package
  post_build:
    commands:
        - echo "build completed..."
  artifacts:
    files:
        - target/hello-world.war
    discard-paths: yes                


            

 --image=coolgourav147/nginx-custom



apiVersion: v1
kind: Pod 

metadata: 
  name: firstpod
  labels: 
     env: prod
     name: swapnil
spec: 
  containers:
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      env: 
        - name: owner
          value: swapnil
          name: city 
          value: pune 
      args: ["sleep","3600"]  
    - name: secondcontainer
      image: coolgourav147/nginx-custom
      env: 
        - name: name
          value: swapnil
          name: city 
          value: nagpur
      args: ["sleep","3600"]
  initContainers:
    - name: init1container
      image: coolgourav147/nginx-custom
      env: 
        - name: name
          value: swapnil
          name: city 
          value: nagpur
      args: ["sleep","15"] 
    - name: init2container
      image: coolgourav147/nginx-custom
      env: 
        - name: name
          value: swapnil
          name: city 
          value: nagpur
      args: ["sleep","15"]






apiVersion: v1
kind: Service

metadata:
      name: firstservice
      labels:
        servicelabel: label1
spec:
      type: NodePort
      port:
        - nodePort: 32000
          port: 9000
          targetPort: 80
      selector:
          type: app



apiVersion: v1
kind: ReplicationController

metadata:
    name: firstrc
    labels:
      appname: app
spec:
    replicas: 5
    selector:
        type: app
    template:
        metadata: 
          name: firstpod
          labels: 
            env: prod
            name: swapnil
            type: app
        spec: 
          containers:
            - name: firstcontainer
              image: coolgourav147/nginx-custom
              env: 
                - name: owner
                  value: swapnil
    



apiVersion: apps/v1
kind: ReplicaSet

metadata:
    name: firstrs
    labels:
      appname: app
spec:
    replicas: 5
    selector:  
        matchLabels: 
          type: app
    template:
        metadata: 
          name: firstpod
          labels: 
            env: prod
            name: swapnil
            type: app
        spec: 
          containers:
            - name: firstcontainer
              image: coolgourav147/nginx-custom
              env: 
                - name: owner
                  value: swapnil



apiVersion: apps/v1
kind: ReplicaSet

metadata:
    name: firstrs
    labels:
      appname: app
spec:
    replicas: 5
    selector:  
      matchExpressions:
        key: app 
        operator: In 
        values:
          - app 
          - app2
          - app3

    template:
      metadata: 
        name: firstpod
          labels: 
            type: app       
      spec: 
        containers:
            name: firstcontainer
            image: coolgourav147/nginx-custom
               
#--------------------------------------------


apiVersion: v1
kind: ResourceQuota
metadata: 
  name:  myquota

spec:
  hard:
    pods: 2



apiVersion: v1
kind: ResourceQuota
metadata: 
  name:  myquota1

spec:
  hard:
    requests.cpu: 0.5
    requests.memory: 200Mi
    limits.cpu: 1
    limits.memory: 1Gi




apiVersion: v1
kind: ResourceQuota
metadata: 
  name:  myquota1

spec:
  hard:
    pods: 10
    requests.cpu: 0.5
    requests.memory: 200Mi
    limits.cpu: 1
    limits.memory: 1Gi


   
apiVersion: v1 
kind:  LimitRange
metadata:
  name: testlimit
  namespace: my-namespace
spec:
  limits: 
    - default:
        cpu: 200m 
        memory: 300Mi
      type: Container   