>
*ref_https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

>A DaemonSet are similar to the Deployments or RS, what is make it different that Deployment or RS is that,
>it ensures that all (or some) Nodes in the cluster will run at least one copy of a Pod. 

>As nodes are added to the cluster, Pods are added to them. As nodes are removed from the cluster, 
>those Pods are garbage collected. 
>Deleting a DaemonSet will clean up the Pods it created.

>Both replica set and deployments are used for running a specific numbers of pods on k8s cluster,
>however, it do not gaurentees the pod creation on all the nodes available in cluster.
 
>but certain cases exist , where we want to run a pod on each and every node, that exist in a cluster,
>and such node needs to run a exactly one instance only.

>In a simple case, one DaemonSet, covering all nodes, would be used for each type of daemon. 
>A more complex setup might use multiple DaemonSets for a single type of daemon, but with different
>flags and/or different memory and cpu requests for different hardware types


Some typical uses of a DaemonSet are:
>running a cluster storage daemon, such as Glustered, Ceph on every node.
>running a logs collection daemon, such as Filebeat, Fluented on every node.
>running a node monitoring daemon, such as Nagios, Elk, Prometheous on every node.


apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch

  template:
    metadata:
      labels:
        name: fluentd-elasticsearch  # same as containers

    spec:
      tolerations:                    # these tolerations are to have the daemonset runnable on control plane nodes
      - key: node-role.kubernetes.io/control-plane   # remove them if your control plane nodes should not run pods
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists                  # all the node selector like taints and toleration, affinity are 
        effect: NoSchedule                #optional, just to make sure that pod will not face any issue.
                                          #DS will automatically deploy one pod per node.
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        volumeMounts:
        - name: varlog
          mountPath: /var/log

      terminationGracePeriodSeconds: 30

      volumes:
      - name: varlog
        hostPath:
          path: /var/log



>---------------------------------------------------------------------------------------------------------