>
>Namespace is like seperate virtual space within kubernetes.
>kubernetes cluster may have multiple application deployed within same cluster. In this we can use seperate 
>namespaces for each application deployement, which introduced layer of isolation between them.

>Using namespavce we can put limit on resource usage, which ensure that each application have enough resources, 
>not all resources is consumed by one application only.

to get the k8s resourses which supports namespaces
>kubectl api-resources

to create different namespace
>kubectl create ns <ns-name>      ---> ns/namespace

to create a resource in a namespace other than default ns
>kubectl apply -f <k8s_res.yml> -n <name-space>

>kubectl <option> <resource> *<name>  -n <ns-name>    ---> -n / --namespace, options:- get, delete, apply, ...

to set custon Namespace as defualt
> kubectl config set-context --current --namespace=<ns-name>

To access service in another namespace 
> <*servicename>.<*namespacename>.svc.cluster.local  -->curl it


>we can controll resources in custom namespace in two different ways_(check limit-quota for more)
1> ResourceQuota
>this will set the limits on the number of k8s objects that can be created in given namespace.

2> LimitRange
>This will set the combine limit on the quantity of the compute resource like RAM and CPU
>that can be used by thr k8s object in the given namespace.

> there are two types of quota/limits, 
1) OBJECT BASED QUOTA, where we limit the number of Object that can be created inside the namespace.
2) COMPUTE BASED QUOTA, where we limit the node resources to be used by k8s resource.


#----------------------------------------------------------------------------------------------------------------
>to set namespace in yml_

apiVersion: v1
kind: Pod 

metadata: 
  name: pod1
  labels: 
     appname: app
  namespace: my-namespace     #setting namespace in manifest file.
spec: 
  containers:
    - name: firstcontainer
      image: coolgourav147/nginx-custom



>-----------------------------------------------------------------------------------------------------------------