

apiVersion: v1
kind: Pod


metadata:
  name: podone
  namespace: default
  creationTimestamp: "2022-09-16T10:09:15Z"
  labels:
    appname: app1
    owner: swapnil

  resourceVersion: "347406"
  uid: e3a5ec89-212e-4e88-853c-6e15c6c26899


  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"appname":"app1","owner":"swapnil"},
      "name":"podone","namespace":"default"},"spec":{"containers":[{"env":[{"name":"environment","value":"test"}],
      "image":"nginx","name":"appcontainer"}]}}


spec:
  containers:
  - env:
    - name: environment
      value: test
    image: nginx
    imagePullPolicy: Always
    name: appcontainer

    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File

    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9tm77
      readOnly: true

  dnsPolicy: ClusterFirst
  enableServiceLinks: true

  nodeName: minikube

  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30

  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-9tm77
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
          
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-16T10:09:15Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-16T10:09:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-16T10:09:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-16T10:09:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0dcde317d8b28daa315897671d37b37284bb66add21202afb244971eb8b42a77
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:0b970013351304af46f322da1263516b188318682b2ab1091862497591189ff1
    lastState: {}
    name: appcontainer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-09-16T10:09:25Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 172.17.0.7
  podIPs:
  - ip: 172.17.0.7
  qosClass: BestEffort
  startTime: "2022-09-16T10:09:15Z"