>
If there are external IPs/ External Name that route to one or more cluster nodes, 
Kubernetes services can be exposed on those externalIPs. 
Traffic that ingresses into the cluster with the external IP(as destination IP)/External Name, 
on the service port, will be routed to one of the service endpoints. 
externalIPs are not managed by Kubernetes and are the responsibility of the cluster administrator.


>EXTERNAL NAME_

>Services of type ExternalName map a Service to a DNS name, not to a typical selector 
>such as my-service or cassandra. You specify these Services with the spec.externalName parameter.

>This Service definition, for example, maps the my-service Service in the prod namespace 
>to my.database.example.com

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: my.database.example.com   

>so , in nutshell, we use texternal service in a case where, we want our service to resolve to the DNS name
>instead of local selector.


>--------------------------------------------------------------------------------------------------------------

ExternalName accepts an IPv4 address string, but as a DNS name comprised of digits, 
not as an IP address. ExternalNames that resemble IPv4 addresses are not resolved by 
CoreDNS or ingress-nginx because ExternalName is intended to specify a canonical DNS name. 
To hardcode an IP address, consider using headless Services.


>EXTERNAL IP_

If there are external IPs that route to one or more cluster nodes, Kubernetes Services 
can be exposed on those externalIPs. Traffic that ingresses into the cluster with the 
external IP (as destination IP), on the Service port, will be routed to one of the Service endpoints. 
externalIPs are not managed by Kubernetes and are the responsibility of the cluster administrator.

In the Service spec, externalIPs can be specified along with any of the ServiceTypes. 
In the example below, "my-service" can be accessed by clients on "80.11.12.10:80" (externalIP:port)

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
  externalIPs:
    - 80.11.12.10

>--------------------------------------------------------------------------------------------------------------